name: SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: Install deps
        run: npm install brew --force
      - name: Install deps
        run: brew cask install adoptopenjdk/openjdk/adoptopenjdk8 android-studio ngrok   
        
      - name: Install deps
        run: yarn install --ignore-engines   
        
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew    
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: cd android && ./gradlew assembleRelease
